### ISSUE TITLE
Other ways to route audio

### ISSUE THREAD

**Issue by ankitkumar93** [technited/AudioRouter#3]
Try to come up with other "good" ways to route audio from any application to any other voice communication application ( can involve routing audio to mic, or can also be just routing audio to that app without using the mic). Provide (if any):
1) Methods
2) Frameworks and Libraries
3) Implementation Plan

Make sure its better than what we are currently planning to do.

**Comment by rokrapoorv** [comment]
**I AM MENTIONING ALL THE RESOURCES I HAVE GATHERED WHICH ARE USEFUL FOR ACHIEVING OUR TARGET**
Our main objective is to route audio stream from one PC to other PCs connected on network provided the 'server' PC don't act as standalone workstation.
This can be achieved by two methods:
**1) PIPELINE THE AUDIO STREAM INTO MICROPHONE.**
We need to make sure that user can still use microphone while he broadcasting some audio data          through his microphone. The output from microphone will be streamed to other user which can connected to the 'server' user (connected on Skype, Discord etc). 

**METHOD**

 Enabling loopback output in audio device manager of the system.
We can code for enabling loopback output which will enable user to stream his own recordings as well play audio stream from his PC.
For windows, http://www.howtogeek.com/217348/how-to-record-the-sound-coming-from-your-pc-even-without-stereo-mix/
For linux, http://askubuntu.com/questions/229352/how-to-record-output-to-speakers
_Problem_
It may lead to Echo on the audio channel which can be significant if there are multiple users.
**2) CREATING A VIRTUAL AUDIO DEVICE**
 In this method, A virtual audio device is deployed on the PC which is independent of hardware.
Audio can be streamed through this device. It requires suitable driver in order to use it.

**METHOD**

- Using a software to direct audio stream through virtual device. 

Some useful software are mentioned in given link :-http://superuser.com/questions/190093/how-to-play-mp3-files-into-the-microphone-input
_Problem_
The audio streaming will become software dependent process which ultimately restricts our objective of implementing the same in our own way. Moreover, user can do this by simply installing the software which defeats our purpose.
- Creating our own virtual device using existing libraries, driver samplers.

1) PortAudio (My preference)
PortAudio is crossplatform, open source audio I/O library which can be used to create virtual device. It provides API to simply call functions. It offers playback option which enables user to stream his recordings through microphone as well as output audio data from system itself simultaneously.
Git repository:https://app.assembla.com/spaces/portaudio/git/source
_Tasks_
We have go through its documentation thoroughly.
We have to build the whole application from scratch and develop its API.

2) Using windows audio sample drivers.
System Virtual Audio Device Driver Sample (SYSVAD) allows us to deploy WDW audio driver which supports multiple audio device.
Its uses and documentation are given in this link:-https://github.com/Microsoft/Windows-driver-samples/tree/master/audio/sysvad
_Problem_
It specifically runs on windows 7 and above.
It is not cross platform.

3) SynchronousAudioRouter
This is another audio driver which also allows user to route audio through digital workstation software. ASIO driver is needed for this.
Documentation can be found in the given link.
https://github.com/eiz/SynchronousAudioRouter/blob/master/README.md
_Problem_
It runs on windows os only.

4) Jack2
It is C++ implementation of JACK low latency audio driver which also serves same purpose.
It uses PortAudio or ASIO driver.
Documentation can be found in the given link.
https://github.com/jackaudio/jack2/blob/master/README
_Problem_
It has bugs while handling multiple threads i.e. users may stuck when quitting the application.

**Comment by vasumahesh1** [comment]
Synchronous Audio Router is really great. It does exactly what we want. The issues are:

1) I don't think there is a CLI exposed interface
2) It runs on Windows because its using the newer WaveRT rather than the older windows api (So it's really fast, and less effort for devs in making a Audio driver)
3) It's mainly targeting DAW (Desktop Audio Workstation)

---

Here is what we want:

1) Aim is to build a C Lib cross platform or platform specific. In the latter case we build drivers based on platforms.

We need to provide APIs like:

```bash
ar --install-device "DeviceID" # Followed by many other options

ar --start-route "MyRouteID" "Source" "Destination"
# Source can be a ARD, File etc.
# Destination can be a ARD, File etc.
# ARD - Audio Router Device - the virtual drivers we install
ar --end-route "MyRouteID"

ar --uninstall-device
```

These are probably the most minimal API we can give.

**Comment by ankitkumar93** [comment]
Looks like the best possible method is to go for building a C Lib using Port Audio only. Rest of the libs are either based on port audio themselves, or have dependencies. So, lets consider the port audio method and work on that.
